import cv2
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import QTimer
from PyQt5.QtWidgets import *

from Main_Window.Timer import *
from Main_Window.LiveFeed import *

class Ui_MainWindow(QMainWindow):
    def setupUi(self):
        self.setWindowTitle("MainWindow")
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.screenshot = QtWidgets.QPushButton("Take a screenshot", self.centralwidget)
        self.screenshot.setGeometry(QtCore.QRect(150, 470, 171, 23))
        self.screenshot.setObjectName("screenshot")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(570, 110, 101, 41))
        self.lcdNumber.setObjectName("lcdNumber")
        self.pause = QtWidgets.QPushButton("Pause", self.centralwidget)
        self.pause.setGeometry(QtCore.QRect(570, 230, 75, 23))
        self.pause.setObjectName("pause")
        self.stop = QtWidgets.QPushButton("Stop", self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(650, 230, 75, 23))
        self.stop.setObjectName("stop")
        self.start = QtWidgets.QPushButton("Start", self.centralwidget)
        self.start.setGeometry(QtCore.QRect(490, 230, 75, 23))
        self.start.setObjectName("start")
        self.usbConnectedLabel = QtWidgets.QLabel("USB status: ", self.centralwidget)
        self.usbConnectedLabel.setGeometry(QtCore.QRect(600, 400, 181, 16))
        self.usbConnectedLabel.setObjectName("usbConnectedLabel")
        self.voltmeter = QtWidgets.QLabel("Voltmeter : N/A", self.centralwidget)
        self.voltmeter.setGeometry(QtCore.QRect(600, 420, 191, 20))
        self.voltmeter.setObjectName("voltmeter")
        self.current = QtWidgets.QLabel("Current sensor: N/A", self.centralwidget)
        self.current.setGeometry(QtCore.QRect(600, 440, 191, 20))
        self.current.setObjectName("current")
        self.leakage = QtWidgets.QLabel("Leakage sensor: N/A", self.centralwidget)
        self.leakage.setGeometry(QtCore.QRect(600, 460, 171, 20))
        self.leakage.setObjectName("leakage")
        self.rMotorState = QtWidgets.QLabel("R-Motor state: Clockwise", self.centralwidget)
        self.rMotorState.setGeometry(QtCore.QRect(600, 480, 191, 20))
        self.rMotorState.setObjectName("rMotorState")
        self.lMotorState = QtWidgets.QLabel("L-Motor state: Clockwise", self.centralwidget)
        self.lMotorState.setGeometry(QtCore.QRect(600, 500, 181, 20))
        self.lMotorState.setObjectName("lMotorState")
        self.motorSpeed = QtWidgets.QLabel("Motor speed: Lowest", self.centralwidget)
        self.motorSpeed.setGeometry(QtCore.QRect(600, 520, 171, 20))
        self.motorSpeed.setObjectName("motorSpeed")
        self.camera = QtWidgets.QLabel("Camera", self.centralwidget)
        self.camera.setGeometry(QtCore.QRect(50, 30, 351, 391))
        self.camera.setFrameShape(QtWidgets.QFrame.Box)
        self.camera.setLineWidth(2)
        self.camera.setObjectName("camera")
        self.secondsBox = QtWidgets.QSpinBox(self.centralwidget)
        self.secondsBox.setGeometry(QtCore.QRect(620, 190, 42, 22))
        self.secondsBox.setObjectName("secondsBox")
        self.minutesBox = QtWidgets.QSpinBox(self.centralwidget)
        self.minutesBox.setGeometry(QtCore.QRect(500, 190, 42, 22))
        self.minutesBox.setObjectName("minutesBox")
        self.minutesLabl = QtWidgets.QLabel("Minutes", self.centralwidget)
        self.minutesLabl.setGeometry(QtCore.QRect(560, 190, 47, 13))
        self.minutesLabl.setObjectName("minutesLabl")
        self.secondsLabel = QtWidgets.QLabel("Seconds", self.centralwidget)
        self.secondsLabel.setGeometry(QtCore.QRect(680, 190, 47, 13))
        self.secondsLabel.setObjectName("secondsLabel")
        self.motionMapButton = QtWidgets.QPushButton("Motion Map", self.centralwidget)
        self.motionMapButton.setGeometry(QtCore.QRect(470, 300, 291, 28))
        self.motionMapButton.setObjectName("motionMapButton")
        self.diffButton = QtWidgets.QPushButton("Spot the difference", self.centralwidget)
        self.diffButton.setGeometry(QtCore.QRect(470, 340, 141, 28))
        self.diffButton.setObjectName("diffButton")
        self.trackingButton = QtWidgets.QPushButton("Object Tracking", self.centralwidget)
        self.trackingButton.setGeometry(QtCore.QRect(620, 340, 141, 28))
        self.trackingButton.setObjectName("trackingButton")
        self.setCentralWidget(self.centralwidget)
        self.start.clicked.connect(readTimer)
        self.timer = QTimer()
        self.timer.timeout.connect(setTimer)
        self.screenshot.clicked.connect(save)
        self.stop.clicked.connect(stopFun)
        self.pause.clicked.connect(pauseFun)
        self.camera.setScaledContents(True)
        self.cap = cv2.VideoCapture(0)
        self.timer1 = QTimer()
        self.timer1.timeout.connect(showCamera)
        self.timer1.start(20)
        self.startTimer = True
        QtCore.QMetaObject.connectSlotsByName(self)
